### ISSUE TITLE
The bot was working fine for some days after that it started giving me error. I tried to reauthorize but the problem was not fixed 

### ISSUE THREAD

**Issue by okaybro526-1** [oVo-HxBots/Utubeitbot#4]
Error occuered during upload.
Error details: <HttpError 403 when requesting None returned "Access forbidden. The request may not be properly authorized.". Details: "[{'message': 'Access forbidden. The request may not be properly authorized.', 'domain': 'youtube.common', 'reason': 'forbidden'}]">

**Comment by oVo-HxBots** [comment]
This error is from google cloud end. Please try to recheck all the details of your project in gcp.
